myEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: 
    DisableApiTermination: 
    ImageId: 
    InstanceType: 
    Monitoring: true|false
    SecurityGroupIds:
      - sg-id
    UserData: !Base64 |
      #!/bin/bash -ex
      # put your script here
    Tags:
      - Key: key
        Value: value
    BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeType: gp2
          VolumeSize: '30'
          DeleteOnTermination: 'false'
          Encrypted: 'true'
