


Parameters:
  SecurityGroups:
    Type: 
    Description: 


Resources:
  my-elb:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - sg-id
      Subnets:
        - subnet-id
      Instances:
        - instance-id
      Listeners:
        - LoadBalancerPort: 80 
          InstancePort: 80
          Protocol: HTTP
          InstanceProtocol: HTTP
      HealthCheck:
        Target: TCP:port or HTTPS|HTTP:port/PathToPing
        HealthyThreshold: 2
        Interval: 300
        Timeout: 2
        UnhealthyThreshold: 2 

  my-tg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: Boolean
      HealthCheckIntervalSeconds: Integer
      HealthCheckPath: String
      HealthCheckPort: String
      HealthCheckProtocol: String
      HealthCheckTimeoutSeconds: Integer
      HealthyThresholdCount: Integer
      Matcher: 
        Matcher
      Name: String
      Port: Integer
      Protocol: String
      Tags: 
        - Tag
      TargetGroupAttributes: 
        - TargetGroupAttribute
      Targets: 
        - TargetDescription
      TargetType: String
      UnhealthyThresholdCount: Integer
      VpcId: String

